# Crowi installer for Vagrant
- hosts: all
  remote_user: vagrant
  vars:
    nvm_version: v0.29.0
    node_version: v4.2.4
    repo_dir: /vagrant/crowi
    branch: master
  tasks:
    - name: Add Elastic apt-key
      sudo: yes
      apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
    - name: Add Elasticsearch apt repo
      sudo: yes
      apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present
    - name: apt-get update
      sudo: yes
      apt: update_cache=yes
    - name: install packages
      sudo: yes
      apt: name={{ item }} install_recommends=no
      with_items:
        - curl
        - elasticsearch
        - g++
        - git
        - mongodb
        - openjdk-7-jdk
    - name: start Elasticsearch
      sudo: yes
      service: name=elasticsearch state=restarted enabled=yes
    - name: Is analysis-kuromoji plugin exists?
      sudo: yes
      stat: path=/usr/share/elasticsearch/plugins/analysis-kuromoji
      register: kuromoji_dir
    - name: Install analysis-kuromoji plugin
      when: not kuromoji_dir.stat.exists
      sudo: yes
      #raw: /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
      command: /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
      register: result
    - name: Restart Elasticsearch
      when: not result|skipped
      sudo: yes
      service: name=elasticsearch state=restarted
    - name: setup nvm using 'raw' module. this is dangerous !!
      raw: /usr/bin/curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | bash
    - name: install nodejs
      raw: . ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}
    - git: repo=ssh://git@github.com/crowi/crowi.git
           dest={{ repo_dir }}
           version={{ branch }}
           accept_hostkey=yes
    - raw: . ~/.nvm/nvm.sh && cd {{ repo_dir }} && export CI=true && npm install
